project:
  type: website

website:
  title: "Energía Renovable"
  navbar:
    left:
      - text: "Inicio"
        href: index.qmd
      - text: "Limpieza de Datos"
        href: data_cleaning.qmd
      - text: "Visualizaciones"
        href: data_view.qmd